# SpiNNaker Nengo Pushbot Integration
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
# ----------------------------------------------------------------------------

APP = pushbot_compass_calibrate
APP_OUTPUT_DIR = $(PWD)/../../nengo_pushbot/binaries/
SOURCES = compass.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
