# SpiNNaker Nengo Pushbot Integration
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
# ----------------------------------------------------------------------------

APP = pushbot_countspikes
APP_OUTPUT_DIR = $(PWD)/../../nengo_pushbot/binaries/
SOURCES = countspikes.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
