# Get the SpiNNaker install directory, Neuron Modelling
SPINN_NM_DIRS=${SPINN_DIRS}/../neural_modelling

OBJECTS += ${SPINN_NM_DIRS}/common/configuration.o ${SPINN_NM_DIRS}/common/spin1-api-configuration.o
CFLAGS += -I ${SPINN_NM_DIRS}/common/ -I ${SPINN_NENGO_DIRS}/common/
CFLAGS += -Wall -Wextra -Ofast

include ${SPINN_NM_DIRS}/Makefile.depend
