# SpiNNaker Nengo Pushbot Integration
# Tracks Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# April 2014
# ----------------------------------------------------------------------------

APP = nengo_pushbot_tracks
SOURCES = tracks-main.c tracks-input.c
OBJECTS = $(SOURCES:.c=.o)

include ../Makefile.depend
