# SpiNNaker Nengo Pushbot Integration
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
# ----------------------------------------------------------------------------

APP = pushbot_tracker
APP_OUTPUT_DIR = $(PWD)/../../nengo_pushbot/binaries/
SOURCES = tracker_update.c tracker.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
